spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}

workly:
  security:
    secret: ${JWT_SECRET}
    header-string: 'Authorization'
    token-prefix: 'Bearer '
    expiration-time: ${JWT_EXP_TIME}
  swagger:
    contact:
      name: 'Michał Dudek'
      url: 'https://instagram.com/_mikovsky_/'
      email: 'dudek.michal1996@gmail.com'
    apinfo:
      title: 'Workly Backend API'
      description: 'Backend API for Workly application'
      version: '1.0.0'
