name: Run Tests
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: workly_db
          POSTGRES_USER: workly_user
          POSTGRES_PASSWORD: workly_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Run Tests
        id: run-tests
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
